In [1]:
import sys
import os   
import graphviz
import pydotplus 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import scipy as sp
from sklearn import tree
from sklearn.model_selection import KFold
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import ExtraTreesClassifier #导入ExtraTrees

In [3]:
def haversine(df):
    lat1 = subway['lat']
    lat2 = df['latitude']
    lon1 = subway['lon']
    lon2 = df['longitude']
    dlat = np.deg2rad(np.fabs(lat2-lat1))
    dlon = np.deg2rad(np.fabs(lon2-lon1))
    a = np.sin(dlat/2)**2 + np.cos(np.deg2rad(lat1))*np.cos(np.deg2rad(lat2))*np.sin(dlon/2)**2
    c =2 * np.arcsin(np.sqrt(a))
    Earth_Radius = 6371
    res = min(c * Earth_Radius * 1000)
    return res

In [4]:
train = pd.read_json('final_train.json')
test = pd.read_json('final_test.json')

In [5]:
subway = pd.read_csv('subway.csv')
subway = subway[['Station Latitude','Station Longitude']]
subway = subway.drop_duplicates()
subway = subway.rename(columns={'Station Latitude':'lat','Station Longitude':'lon'})
train['distance_subway'] = train.apply(haversine,axis = 1)
test['distance_subway'] = test.apply(haversine,axis = 1)

In [7]:
train

,rec_id,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,...,ft_fitnesscenter,ft_hardwoodfloors,ft_laundryinbuilding,ft_laundryinunit,ft_nofee,manager_id_num,building_id_num,photo_num,clean_feat,distance_subway
0,4,1.0,1,8579a0b0d54db803821a35a4a615e97a,1466056527000,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,...,0.333857,0.262237,0.604220,0.359662,0.243498,2762,6071,12,DiningRoom Pre-War LaundryinBuilding Dishwashe...,304.673389
1,6,1.0,2,b8e75fc949a6cd8225b455648a951712,1464759873000,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,...,0.000000,0.000000,0.820373,0.000000,0.266732,2560,8401,6,Doorman Elevator LaundryinBuilding Dishwasher ...,323.876878
2,9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,1465917599000,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,...,0.000000,0.205013,0.000000,0.590085,0.190364,3452,9327,6,Doorman Elevator LaundryinBuilding LaundryinUn...,552.143820
3,10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,1466754864000,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,...,0.428754,0.336776,0.000000,0.000000,0.312711,1565,3788,5,,131.089810
4,15,1.0,0,bfb9405149bfff42a92980b594c28234,1467085823000,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,...,0.000000,0.000000,0.000000,0.000000,1.000000,790,8701,4,Doorman Elevator FitnessCenter LaundryinBuilding,698.529082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49347,124000,1.0,3,92bbbf38baadfde0576fc496bd41749c,1459828713000,There is 700 square feet of recently renovated...,W 171 Street,"[Elevator, Dishwasher, Hardwood Floors]",40.8433,6824800,...,0.317435,0.249338,0.339309,0.341971,0.231521,2850,6638,5,Elevator Dishwasher HardwoodFloors,287.012856
49348,124002,1.0,2,5565db9b7cba3603834c4aa6f2950960,1459563931000,"2 bedroom apartment with updated kitchen, rece...",Broadway,"[Common Outdoor Space, Cats Allowed, Dogs Allo...",40.8198,6813268,...,0.404119,0.317426,0.000000,0.000000,0.618553,2451,3877,5,CommonOutdoorSpace CatsAllowed DogsAllowed NoF...,425.094259
49349,124004,1.0,1,67997a128056ee1ed7d046bbb856e3c7,1461649323000,No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...,210 Brighton 15th St,"[Dining Room, Elevator, Pre-War, Laundry in Bu...",40.5765,6927093,...,0.353395,0.000000,0.000000,0.380710,0.257748,2762,4728,3,DiningRoom Elevator Pre-War LaundryinBuilding ...,519.874244
49350,124008,1.0,2,3c0574a740154806c18bdf1fddd3d966,1461034053000,Wonderful Bright Chelsea 2 Bedroom apartment o...,West 21st Street,"[Pre-War, Laundry in Unit, Dishwasher, No Fee,...",40.7448,6892816,...,0.419652,0.329626,0.448569,0.000000,0.306072,3372,2723,5,Pre-War LaundryinUnit Dishwasher NoFee Outdoor...,331.873686
49351,124009,1.0,3,d89f514c3ed0abaae52cba7017ac0701,1461130440000,***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...,E 54th St,"[Dining Room, Elevator, Laundry in Building, D...",40.7594,6901023,...,0.000000,0.388792,0.000000,0.000000,0.361010,3991,9869,8,DiningRoom Elevator LaundryinBuilding Dishwash...,262.082629

In [8]:
train.to_json('bonus_train.json')
test.to_json('bonus_test.json')